### ISSUE TITLE
About

### ISSUE THREAD

**Issue by godmehhhh** [YoZhibo/MSGNet#1]
你好，想要一份flight的数据集

**Comment by YoZhibo** [comment]
您好，已在readme更新，您可以从[Google Drive](https://drive.google.com/drive/folders/1JSZByfM0Ghat3g_D3a-puTZ2JsfebNWL?usp=sharing)中获取。

**Comment by godmehhhh** [comment]
您好，这份数据的'OT'，也就是真实值y是哪个列

**Comment by YoZhibo** [comment]
我们设置”UUEE“作为OT。
