### ISSUE TITLE
FFT计算出的scale为什么没有传入ScaleGraphBlock模块，来实现论文中的Multi-scale Adaptive Graph Convolution

### ISSUE THREAD

**Issue by pipiccsam** [YoZhibo/MSGNet#12]
![2024-07-15_171027](https://github.com/user-attachments/assets/fd2a909b-b1b5-4882-89a8-2c647348426a)

Why is the scale calculated by the FFT not passed into the ScaleGraphBlock module to implement the Multi-scale Adaptive Graph Convolution in the paper

FFT计算出的scale为什么没有传入ScaleGraphBlock模块，来实现论文中的Multi-scale Adaptive Graph Convolution

**Comment by YoZhibo** [comment]
您好，感谢关注。scale处于ScaleGraphBlock中，我们认为不同graph在这个过程中施加给了不同的scale，使模型能够学习到多尺度信息。
