### ISSUE TITLE
怎么去复现您的项目呢？

### ISSUE THREAD

**Issue by Jeff-Zhu-520** [YoZhibo/MSGNet#18]
可否给一个requirement文件，我是初学者，直接下载code到pycharm去尝试复现感觉遇到了很多问题

**Comment by YoZhibo** [comment]
pandas==1.5.3
scikit-learn==1.2.1
numpy==1.23.5
torch==2.0.1
matplotlib==3.8.0
einops==0.7.0
sktime==0.28.1
scipy==1.10.0
sympy==1.11.1
tqdm==4.64.1
您好，可以参考这个配置。关于pytorch可以到 https://pytorch.org/get-started/previous-versions/ 进行下载，或者选择适配您cuda版本的pytorch。
