### ISSUE TITLE
请问还有其他的数据集吗？

### ISSUE THREAD

**Issue by kerwinqil** [YoZhibo/MSGNet#19]
请问可否提供一下除了Flight.csv以外的其他数据集，谢谢！

**Comment by YoZhibo** [comment]
您好，已在 [Google Drive](https://drive.google.com/drive/folders/1JSZByfM0Ghat3g_D3a-puTZ2JsfebNWL?usp=sharing) 上传其他数据集。

**Comment by kerwinqil** [comment]
非常感谢您的回应，祝您科研顺利!
