### ISSUE TITLE
有关Multi-scale Adaptive Graph Convolution

### ISSUE THREAD

**Issue by maxuhuii** [YoZhibo/MSGNet#2]
你好，在ScaleGraphBlock中，Gconv处理的是没有按照尺度进行scale的原始输入x，那如何能保证图卷积过程中利用到了不同尺度的信息？

**Comment by YoZhibo** [comment]
你好，每个graph不同，并施加给了不同scale，我们认为这样可以起到作用，机场的邻接矩阵也验证了模型能够学习到多尺度信息。
