### ISSUE TITLE
？

### ISSUE THREAD

**Issue by zju-xiaoyaoyou** [YoZhibo/MSGNet#21]

**Comment by YoZhibo** [comment]
您好，感谢关注。傅里叶模块是依据当前的输入数据来获取尺度，具体到单个批次，可能会存在不同的情况。而从整体（频率）上看，它们会倾向于特定尺度，用来学习数据集的普遍特征。我们也在Fig 8中对尺度分布进行了展示，希望对您有所帮助。

**Comment by zju-xiaoyaoyou** [comment]
但每次前向传播的前K个振幅最大的scale还是可能不同的，还有就是代码里并没有论文中提到的在送入图卷积之前会根据scale做一次reshape，相当于就是独立的K个自适应图在对输入x处理，那不同scale是如何发挥作用呢？
