### ISSUE TITLE
关于test results图的问题

### ISSUE THREAD

**Issue by Jeff-Zhu-520** [YoZhibo/MSGNet#22]
<img width="723" alt="微信图片_20241122164654" src="https://github.com/user-attachments/assets/fb0380bc-861a-4a82-af50-eb4cf65c9a12">
您好，请问为什么会有这么多张图，然后为什么偏移会这么大呢？

**Comment by YoZhibo** [comment]
您好，这个来自框架保留下来的绘图函数 [visual](https://github.com/YoZhibo/MSGNet/blob/main/exp/exp_main.py#L263) ，您可以将其注释掉。对于金融数据，波动会比较大，较难进行准确预测。
