### ISSUE TITLE
Question about the adjacency matrices

### ISSUE THREAD

**Issue by Kivirrr** [YoZhibo/MSGNet#5]
Hi, many thanks for contributing such a impressive work! I'm curious about the way you obtained the adjacency matrices you showed for the flight dataset. May I apply these on another multivariable forecasting dataset?

**Comment by YoZhibo** [comment]
Hi, thanks for your attention. You can simply retrieve the values of the trained adjacency matrix and utilize plt to visualize it. For ease of retrieval, you may set the parameter is_training to 0. Additionally, this approach is generally applicable to other multivariate datasets as well.
