### ISSUE TITLE
请问Mixhop order这个超参数出现在代码中的哪里？

### ISSUE THREAD

**Issue by Kivirrr** [YoZhibo/MSGNet#6]
您好，我在parser和msgnet代码中没有看到Mixhop order，请问它出现在哪里呢？感谢！

**Comment by YoZhibo** [comment]
您好，这个参数对应MSGBlock文件第175行的gdep深度，[Link to Line 175 of MSGBlock.py](https://github.com/YoZhibo/MSGNet/blob/main/layers/MSGBlock.py#L175)。
