### ISSUE TITLE
meaning of 'start token length'

### ISSUE THREAD

**Issue by wutengcoding** [YoZhibo/MSGNet#7]
Hello, @YoZhibo 
Really appreciate the incredible work you have done
I want to know why we need a label_len param in basic arg_parse, what is the meaning of 'start token length'
parser.add_argument('--label_len', type=int, default=48, help='start token length')

**Comment by YoZhibo** [comment]
Hi, thank you for your attention. 
Our model doesn't pay attention to this parameter. It is the start token length of decoder, used in models such as Informer. You can refer to this paper [Informer](https://arxiv.org/abs/2012.07436).
